<!doctype html>
<html>
	<head>
		<meta charset="UTF-8">
		<link href="less/style.less" rel="stylesheet/less" type="text/css">
		<script type="text/javascript" src="js/less.js"></script>
		<title>More fun creating sequence diagrams</title>
	</head>
	<body>
		<div class="container">
			<h1 class="center">Have fun creating sequence diagrams! <small>(Yes. We are serious.)</small></h1>

			<p class="intro center">
				Everybody <em>hates creating diagrams</em>. It is one of the <em>most agonized</em> parts of doing a project. Why should a <em>developer become a designer</em> for a few hours, click together icons in an <em>annoying interface</em> that never does what he wants?
			</p>

			<h2 class="center">What if we told you, that you can create diagrams by writing text? <small>(No. we are not mad.)</small></h2>

			<div class="row example">
				<div class="span-one-third">
					<pre>// Sections:
User
Frontend
API
Database

// Actions:
User: Clicks login
Frontend: Verifies data
API: Verifies data
Database: Look up user record
API: Check if password is a match
Frontend: Show result to the user </pre>
				</div>

				<div class="span-one-third image">
					<img src="images/example.png">
				</div>
			</div>

			<div class="row">
				<div class="span8">
					<h3>Can your diagram software do this?</h3>
					<ul>
						<li>Create complete flowcharts within one minute</li>
						<li>Auto-align elements on the page</li>
						<li>Use text to describe the processes</li>
						<li>Integrate with your continuous integration server to automatically create new versions on each commit</li>
						<li>Very fast creation of diagrams</li>
					</ul>
				</div>
				<div class="span8 newsletter">
					<label class="h3" for="mce-EMAIL">Sweet! I'm interested. Tell me more, please.</label>
<form action="http://komola.us2.list-manage2.com/subscribe/post?u=9f0d85a44a0fd99430ed86ad4&amp;id=577971821c" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
	<input type="email" value="" name="EMAIL" class="email xlarge" id="mce-EMAIL" placeholder="Your email address goes here" required>
	<input type="submit" value="Sign me up" name="subscribe" id="mc-embedded-subscribe" class="btn success">
</form>
				</div>
			</div>

			<div class="row">
				<div class="span17 center footer">
					<p class="madein">Made in Braunschweig<span class="black"></span><span class="red"></span><span class="gold"></span></p>
					A <a href="http://komola.de">komola</a> project.
				</div>
			</div>
		</div>
		<script type="text/javascript">

			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-26186437-1']);
			_gaq.push(['_trackPageview']);

			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();

		</script>
	</body>
</html>
